### ISSUE TITLE
Dynamically Adding Clock(s)

### ISSUE THREAD

**Issue by NateDigs** [deepu105/angular-clock#13]
I have an add button. I would like it so when that add button is pushed a clock appears.  Currently when i click my add button it adds an [[object HTMLElement]]

Here is my code currently.  Any help would be appreciated. 
![image](https://user-images.githubusercontent.com/22581571/28749280-35620ef0-747f-11e7-974e-ec76a26c1624.png)

**Comment by NateDigs** [comment]
ive figured this out. you can close this ticket. Posting the solution in case someone else encounters this issue.


![image](https://user-images.githubusercontent.com/22581571/28750262-436c6fc2-74a2-11e7-9cdf-6e768f540ccb.png)

**Comment by deepu105** [comment]
![](https://user-images.githubusercontent.com/22581571/28750262-436c6fc2-74a2-11e7-9cdf-6e768f540ccb.png)
