### ISSUE TITLE
Digital Clock Doesnt Update When using gmt-offset

### ISSUE THREAD

**Issue by dresslerc** [deepu105/angular-clock#5]
I have a Analog + Digital Clock showing via this HTML:

`<ds-widget-clock theme="light" show-secs="true"  gmt-offset="-5" show-analog show-digital digital-format="'hh:mm:ss a'"   ></ds-widget-clock>`

The analog clock is correct, however, the digital clock shows the wrong hour.

**Comment by deepu105** [comment]
Ill take a look

**Comment by deepu105** [comment]
<ds-widget-clock show-digital digital-format="'hh:mm:ss a'"> gmt-offset="5.3" show-gmt-info></ds-widget-clock>


Does this work can you confirm plz

**Comment by deepu105** [comment]
`<ds-widget-clock show-digital digital-format="'hh:mm:ss a'"> gmt-offset="5.3" show-gmt-info></ds-widget-clock>`

Does this work can you check

**Comment by animir** [comment]
I have the same issue with negative timezone offset.
Checked with `gmt-offset="'-08.00'"` (or `gmt-offset="'-8'"`) and `digital-format="'Z'"` and it shows '0008'.

**Comment by animir** [comment]
@deepu105 gmt-offset issue is fixed here https://github.com/deepu105/angular-clock/pull/6

**Comment by deepu105** [comment]
closed via #6
